server {
    listen 80;
    server_name flutterx.itbug.shop;

    root /var/www/flutterx-doc;
    index index.html;

    location / {
        try_files $uri $uri/ $uri/index.html /404.html;
    }

    location /assets/ {
        expires 30d;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }

    location /stylesheets/ {
        expires 30d;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }

    location /javascripts/ {
        expires 30d;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }

    location /search/ {
        expires 1d;
        add_header Cache-Control "public";
        try_files $uri =404;
    }
}
