name: 打包上传
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 京东云 1panel上传
        uses: easingthemes/ssh-deploy@v5.1.0
        env:
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USER }}
          SSH_PRIVATE_KEY: ${{ secrets.PASS }}
          REMOTE_PORT: ${{ secrets.PORT }}
          SOURCE: "webHelpFLUTTERX2-all/"
          TARGET: ${{ secrets.PATH }}